name: Fetch SPY Historical Data

# Allows you to run this workflow manually from the Actions tab
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checks out your repository's code so the job can access it
      - name: Check out repository code
        uses: actions/checkout@v4

      # 2. Sets up a Python environment
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # 3. Installs the necessary Python libraries
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install polygon-api-client pandas

      # 4. Runs the Python script
      - name: Execute data fetch script
        env:
          POLYGON_API_KEY: ${{ secrets.POLYGON_API_KEY }}
        run: python get_data.py

      # 5. Uploads the resulting CSV file as a downloadable artifact
      - name: Upload data artifact
        uses: actions/upload-artifact@v4
        with:
          name: spy-5min-data
          path: SPY_5min_data.csv
