name: Fetch SPY Historical Data (Alpaca)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checks out your repository code
      - name: Check out repository code
        uses: actions/checkout@v4

      # 2. Sets up Python
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # 3. Install the Alpaca library
      - name: Install dependencies
        run: pip install alpaca-py pandas

      # 4. Run the Python script with both Alpaca keys
      - name: Execute data fetch script
        env:
          ALPACA_API_KEY: ${{ secrets.ALPACA_API_KEY }}
          ALPACA_SECRET_KEY: ${{ secrets.ALPACA_SECRET_KEY }}
        run: python get_data.py

      # 5. Upload the resulting CSV file
      - name: Upload data artifact
        uses: actions/upload-artifact@v4
        with:
          name: spy-5min-data-alpaca
          path: SPY_5min_data_alpaca.csv
